name = "mini-pos-system"
type = "javascript"
workers_dev = true
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[env.production]
name = "mini-pos-system-prod"

[site]
bucket = "./public"
entry-point = "server.js"
